version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      prisma:
        patterns:
          - '@prisma/client'
          - 'prisma'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
